pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
    }

    stages {

        stage('Build') {
            steps {
                dir('jenkins-demo') {
                    bat 'mvn clean install'
                }
            }
        }

    }
}